OD-735 [Fix] Fixed styles for search result bubble
Fliplet/fliplet-theme-default pull request #183
Opened 2022-03-01 10:26 UTC by skrupnyk

@romanyosyfiv @inna-bieshulia

OD-643 https://weboo.atlassian.net/browse/OD-643

## Description
**Problem:** Styles for LFD search result bubble did not inherit from highlight color.
**Solution:** Added style inheritance from highlight color.

## Screenshots/screencasts
www.awesomescreenshot.com/video/7652864?key=c99c3b484801be85558a91929b30a813

## Backward compatibility
This change is fully backward compatible.

## Reviewers
@upplabs-alex-levchenko

2022-03-03 13:44 UTC, tonytlwu requested changes

2022-03-03 13:44 UTC, tonytlwu commented on scss/components/lfd/agenda.scss
> +        background-color: $highlightColor;
Use primary button background color

2022-03-03 13:44 UTC, tonytlwu commented on scss/components/lfd/agenda.scss
> +        border-color: $highlightColor;
Use primary button background color

2022-03-03 15:51 UTC, skrupnyk commented on scss/components/lfd/agenda.scss
> +            color: $primaryButtonTextColor;
fixed

2022-03-07 23:05 UTC, tonytlwu approved these changes
@romanyosyfiv @inna-bieshulia This is ready for testing

Risk: Medium
Affected: All LFD layouts with search enabled
Verify: Search terms are highlighted using the correct colours

Squash and merge: Use PR title

2022-03-08 09:13 UTC, merged